// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR5w51rTd9sdPvmGQndIn-Vxb5FZrjYeE',
    appId: '1:816746234784:web:48ddf0c9eb79c505f89ac5',
    messagingSenderId: '816746234784',
    projectId: 'notesapp-4cf30',
    authDomain: 'notesapp-4cf30.firebaseapp.com',
    storageBucket: 'notesapp-4cf30.firebasestorage.app',
    measurementId: 'G-SBWYC649C9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBah_TfnxJABYCJFX-ftvhZgLXcfqv-1Wg',
    appId: '1:816746234784:android:7a27251fb3b4e002f89ac5',
    messagingSenderId: '816746234784',
    projectId: 'notesapp-4cf30',
    storageBucket: 'notesapp-4cf30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqWc3AJIRaN9E4aPt5I2UZR1GLrsbmHkc',
    appId: '1:816746234784:ios:0e5199deaecdcf77f89ac5',
    messagingSenderId: '816746234784',
    projectId: 'notesapp-4cf30',
    storageBucket: 'notesapp-4cf30.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqWc3AJIRaN9E4aPt5I2UZR1GLrsbmHkc',
    appId: '1:816746234784:ios:0e5199deaecdcf77f89ac5',
    messagingSenderId: '816746234784',
    projectId: 'notesapp-4cf30',
    storageBucket: 'notesapp-4cf30.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR5w51rTd9sdPvmGQndIn-Vxb5FZrjYeE',
    appId: '1:816746234784:web:74a433babeb008a4f89ac5',
    messagingSenderId: '816746234784',
    projectId: 'notesapp-4cf30',
    authDomain: 'notesapp-4cf30.firebaseapp.com',
    storageBucket: 'notesapp-4cf30.firebasestorage.app',
    measurementId: 'G-N16RM7WG4R',
  );
}
